# Yellowstone btop palette

theme_background=false
theme[main_bg]=""
theme[main_fg]="#eae5cf"
theme[title]="#c7692d"
theme[hi_fg]="#bda01a"
theme[selected_bg]="#27221a"
theme[selected_fg]="#efecdb"
theme[inactive_fg]="#65635d"
theme[graph_text]="#ede9d6"
theme[meter_bg]="#27221a"
theme[proc_misc]="#cb794e"

theme[cpu_box]="#c7692d"
theme[mem_box]="#b49200"
theme[net_box]="#cc6b35"
theme[proc_box]="#cb794e"
theme[div_line]="#7a492f"

theme[temp_start]="#c7692d"
theme[temp_mid]="#bda01a"
theme[temp_end]="#c2612f"

theme[cpu_start]="#c7692d"
theme[cpu_mid]="#cc6b35"
theme[cpu_end]="#fb8d46"

theme[free_start]="#cc6b35"
theme[free_mid]="#b49200"
theme[free_end]="#ddb900"

theme[cached_start]="#7a492f"
theme[cached_mid]="#cb794e"
theme[cached_end]="#bda01a"

theme[available_start]="#c7692d"
theme[available_mid]="#eae5cf"
theme[available_end]="#bda01a"

theme[used_start]="#bda01a"
theme[used_mid]="#cb794e"
theme[used_end]="#c2612f"

theme[download_start]="#c7692d"
theme[download_mid]="#cc6b35"
theme[download_end]="#fb8d46"

theme[upload_start]="#b49200"
theme[upload_mid]="#bda01a"
theme[upload_end]="#e1c000"

theme[process_start]="#cc6b35"
theme[process_mid]="#bda01a"
theme[process_end]="#c2612f"

theme[gradient_color_0]="#0f0900"
theme[gradient_color_1]="#27221a"
theme[gradient_color_2]="#65635d"
theme[gradient_color_3]="#7a492f"
theme[gradient_color_4]="#c2612f"
theme[gradient_color_5]="#bda01a"
theme[gradient_color_6]="#c7692d"
theme[gradient_color_7]="#efecdb"
