# Yellowstone btop palette

theme_background=false
theme[main_bg]=""
theme[main_fg]="#d4cfb1"
theme[title]="#a9c8df"
theme[hi_fg]="#d7c78f"
theme[selected_bg]="#332c23"
theme[selected_fg]="#dfdbc5"
theme[inactive_fg]="#67635d"
theme[graph_text]="#dad6bd"
theme[meter_bg]="#332c23"
theme[proc_misc]="#d3af96"

theme[cpu_box]="#a9c8df"
theme[mem_box]="#d1bc86"
theme[net_box]="#94bbce"
theme[proc_box]="#d3af96"
theme[div_line]="#7f695a"

theme[temp_start]="#a9c8df"
theme[temp_mid]="#d7c78f"
theme[temp_end]="#cba183"

theme[cpu_start]="#a9c8df"
theme[cpu_mid]="#94bbce"
theme[cpu_end]="#b0d6f6"

theme[free_start]="#94bbce"
theme[free_mid]="#d1bc86"
theme[free_end]="#e7c964"

theme[cached_start]="#7f695a"
theme[cached_mid]="#d3af96"
theme[cached_end]="#d7c78f"

theme[available_start]="#a9c8df"
theme[available_mid]="#d4cfb1"
theme[available_end]="#d7c78f"

theme[used_start]="#d7c78f"
theme[used_mid]="#d3af96"
theme[used_end]="#cba183"

theme[download_start]="#a9c8df"
theme[download_mid]="#94bbce"
theme[download_end]="#b0d6f6"

theme[upload_start]="#d1bc86"
theme[upload_mid]="#d7c78f"
theme[upload_end]="#f0c968"

theme[process_start]="#94bbce"
theme[process_mid]="#d7c78f"
theme[process_end]="#cba183"

theme[gradient_color_0]="#1c150b"
theme[gradient_color_1]="#332c23"
theme[gradient_color_2]="#67635d"
theme[gradient_color_3]="#7f695a"
theme[gradient_color_4]="#cba183"
theme[gradient_color_5]="#d7c78f"
theme[gradient_color_6]="#a9c8df"
theme[gradient_color_7]="#dfdbc5"
